[package]
name = "web-jingzi"
version = "0.2.2"
authors = ["vinoca <vinoca@vinoca.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
smol = "1.2.5"
serde_yaml = "0.8.17"
once_cell = "1.7.0"
async-io = "1.3.1"
async-dup = "1.2.2"
env_logger = "0.8.3"
log = "0.4.14"
async-std = "1.9.0"
async-native-tls = "0.3.3"
async-h1 = "2.3.1"

[dependencies.socks5]
version = "0.2.2"
git = "https://github.com/vincascm/socks5.git"

[dependencies.http-types]
version = "2.10.0"
default-features = false

[dependencies.serde]
version = "1.0.123"
features = ["derive"]

[dependencies.async-compression]
version = "0.3.7"
features = ["brotli", "deflate", "gzip", "futures-io"]
