[package]
name = "web-jingzi"
version = "0.1.1"
authors = ["vinoca <vinoca@vinoca.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
smol = "0.3.3"
serde_yaml = "0.8.13"
once_cell = "1.4.0"
async-io = "0.1.10"
async-h1 = "2.1.2"
async-dup = "1.2.1"
http-types = "2.4.0"
futures = "0.3.5"
env_logger = "0.7.1"
log = "0.4.11"
async-std = "1.6.2"
async-native-tls = "0.3.3"
socks5 = { version = "0.2", git = "https://github.com/vincascm/socks5.git" }

[dependencies.serde]
version = "1.0.114"
features = ["derive"]

[dependencies.async-compression]
version = "0.3.5"
features = ["brotli", "deflate", "gzip", "futures-io"]
