listen_address = "127.0.0.1:80"
# request to corresponding url, like http://x.com -> http://www.google.com, will replace http://www.google.com to https://www.google.com
use_https = [ "x.com",  "y.com" ]
data_dir = "data"
[domain_name]
  "x.com" = "www.google.com"
  "y.com" = "wikipedia.org"
[authorization]
  enabled = true
  domain_list = [ "x.com", "y.com" ]
[[authorization.account]]
    username = "tony"
    password = "123"
